### PR TITLE
Add keybind to save tmux scrollback

### PR DESCRIPTION
**Pull request by ShaneSmiskol**
Just tested this by modifying the file locally, it works!

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you save to another path? I don't want this to mess with logging the tmux output on boot.

**Comment by ShaneSmiskol** [comment]
How's that history limit?

**Comment by adeebshihadeh** [comment]
My only concern is users unknowingly taking up space on their userdata partition since the /tmp on NEOS doesn't get cleared automatically.

**Comment by ShaneSmiskol** [comment]
True, and I think it wipes the file each time you write to it. There was talk a while ago about adding a community folder in `/data` for stuff like this plus a customizable `.bashrc`, and defaulting to `/data/openpilot` on sshing, is that still in the works?

**Pull request merged**
