### PR TITLE
WIP: NEOS 10

### PR DESCRIPTION
**Pull request by pd0wm**
- [x] Build working /usr from scratch
- [x] Figure out why symlink /tmp to -> /usr/tmp is necessary
- [x] Verify all services still work
- [x] Update python packages
- [x] Build arm-none-eabi-gcc from scratch, or switch to clang to compile panda code
- [ ] Update SNPE to 1.25
- [x] Build openvpn

### CODE REVIEW

**Comment by andyh2** [comment]
package requests: `man`, `jq`

**Comment by pd0wm** [comment]
Add nosetests pip package

**Comment by andyh2** [comment]
pip package request: ipython

**Comment by pd0wm** [comment]
Dfu-util

**Comment by pd0wm** [comment]
Request: add tcpdump

**Comment by gregjhogan** [comment]
request: [iperf3](https://software.es.net/iperf/)

**Comment by pd0wm** [comment]
request: nano

**Pull request merged**
